When creating your own promise type, if the type references itself in the `then` method, this error will occur.

```ts
declare class BadPromise {
  then(onfulfilled: (value: BadPromise) => any, onrejected: (error: any) => any): BadPromise;
}

async function test() {
    await new BadPromise()
}
```

To fix the error, don't use a recursive type in the definition of `BadPromise`.

### See also

- [Comment in `src/compiler/checker.ts` near line 25700](https://raw.githubusercontent.com/microsoft/TypeScript/master/src/compiler/checker.ts)
